services:
  - type: web
    name: django-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn backend.wsgi --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: django-insecure-vgv&z5o43^$vm(&-c#1*ym!pr5xn1^qxvy#aze6s(gz!1*f8an
    build:
      context: backend

  - type: web
    name: react-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    staticPublishPath: build
